@isTest
public class allAvailableContactsTest {
    	@isTest
    public Static Void runAsExample() {
        system.debug('ALL CONTACTS :' + allAvailableContacts.getContacts());

        /*
        String uName = 'user' + Datetime.now().getTime() + '@alexrodriguez.tech';
        Profile p = [SELECT id 
                    FROM Profile
                    WHERE name='Minimum Access - Salesforce'];
        User u = new User(alias = 'testUser', email='testuser@alexrodriguez.tech',
                          emailencodingkey='UTF-8', lastname = 'Test', languagelocalekey='en_us',
                          timezonesidkey='america/new_york', localeSidKey='en_us', 
                          profileId=p.id, username=uName);

        System.RunAs(u) {
            ContactShare userContactSharing = new ContactShare();
            system.debug('ALL CONTACTS :' + allAvailableContacts.getContacts());

        } */
    }

    
    
    
}